### ISSUE TITLE
New logo for PokemonGO - ODI

### ISSUE THREAD

**Issue by keyphact** [pkmngo-odi/about#1]
We need a new logo created for the PokemonGO ODI, because the current one is copyrighted.
Final logo should go under a directory called logo in the top most level of the repository.

**Comment by zeeraw** [comment]
My partner will make one tonight. She had a really cool idea about using the "proximity footsteps" from the game as the base. :)

**Comment by keyphact** [comment]
Looking forward to it :dancer:
